### ISSUE TITLE
Issue with CSS files and PostCSS plugin

### ISSUE THREAD

**Issue by nikolay-borzov** [badcafe/rollup-plugin-inject-process-env#4]
Config file looks like 
```javascript
const path = require('path');
const rollup = require('rollup');
const injectProcessEnv = require('rollup-plugin-inject-process-env');
const resolve = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const typescript = require('rollup-plugin-typescript2');
const postcss = require('rollup-plugin-postcss');
const { terser } = require('rollup-plugin-terser');

async function getCode() {
  const bundle = await rollup.rollup({
    input: path.resolve(__dirname, 'index.tsx'),
    plugins: [
      injectProcessEnv({
        NODE_ENV: 'production',
      }),
      resolve({
        browser: true,
      }),
      commonjs(),
      typescript({
        tsconfig: path.resolve(__dirname, './tsconfig.json'),
      }),
      terser(),
      postcss({
        inject: true,
        minimize: true,
        plugins: [],
      }),
    ],
  });

  const { output } = await bundle.generate({
    format: 'iife',
    sourcemap: false,
  });

  ...
}
```

> UnhandledPromiseRejectionWarning: CssSyntaxError: C:\develop\src\client\index.css:1:1: Unknown word
    at Input.error (C:\develop\node_modules\postcss\lib\input.js:130:16)
    at Parser.unknownWord (C:\develop\node_modules\postcss\lib\parser.js:563:22)
    at Parser.other (C:\develop\node_modules\postcss\lib\parser.js:168:12)
    at Parser.parse (C:\develop\node_modules\postcss\lib\parser.js:77:16)
    at parse (C:\develop\node_modules\postcss\lib\parse.js:17:12)
    at new LazyResult (C:\develop\node_modules\postcss\lib\lazy-result.js:60:16)
    at Processor.<anonymous> (C:\develop\node_modules\postcss\lib\processor.js:138:12)
    at Processor.process (C:\develop\node_modules\postcss\lib\processor.js:117:23)
    at C:\develop\node_modules\rollup-plugin-postcss\dist\index.js:212:45
    at Generator.next (<anonymous>)

I suppose it happens because the plugin imports JS module inside each module. This issue could be avoided with `exclude` option but the plugin doesn't support one

**Comment by ppoulard** [comment]
Fixed in v1.3.0
